[package]
org = "ballerinax"
name = "sfdc"
version = "2.1.10"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["sfdc", "salesforce"]
repository = "https://github.com/ballerina-platform/module-ballerinax-sfdc"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../emp-wrapper/target/emp-wrapper-2.1.10.jar"
groupId = "org.ballerinalang.sf"
artifactId = "emp-wrapper"
module = "emp-wrapper" 
version = "2.1.10"
