[package]
org = "ballerinax"
name = "sfdc"
version = "2.2.0"
export = ["sfdc", "sfdc.bulk", "sfdc.soap"]
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["sfdc", "salesforce"]
repository = "https://github.com/ballerina-platform/module-ballerinax-sfdc"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../emp-wrapper/build/libs/emp-wrapper-2.2.0-all.jar"
groupId = "org.ballerinalang.sf"
artifactId = "emp-wrapper"
module = "emp-wrapper" 
version = "2.2.0"
