[package]
distribution = "2201.0.0"
org = "ballerinax"
name = "salesforce"
version = "4.2.0"
export = ["salesforce", "salesforce.bulk", "salesforce.soap"]
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Sales & CRM/Customer Relationship Management", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-sfdc"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../emp-wrapper/build/libs/emp-wrapper-4.2.0-all.jar"
groupId = "org.ballerinalang.sf"
artifactId = "emp-wrapper"
module = "emp-wrapper" 
version = "4.2.0"
