[project]
org-name= "ballerinax"
version= "2.1.2"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["ballerina", "salesforce", "sfdc", "client", "connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-sfdc"

[platform]
target = "java8"

  [[platform.libraries]]
  module = "sfdc"
  path = "../emp-wrapper/target/emp-wrapper-2.1.2.jar"
